-- Tables Creation

CREATE TABLE ADMINISTRATOR_TABLE_1(
    admin_Id INT NOT NULL PRIMARY KEY,
    admin_Name VARCHAR(50),
    passwrd VARCHAR(50)
);


-- PERSONAL DETAILS TABLE
CREATE TABLE PERSONAL_DETAILS_TABLE_2(
    first_Name VARCHAR(30) NOT NULL,
    last_Name VARCHAR(30) NOT NULL,
    Aadhar_Number VARCHAR(12) NOT NULL PRIMARY KEY,
    Date_Of_Birth VARCHAR(12) NOT NULL,
    phone_No VARCHAR(10) NOT NULL,
    Email_Id VARCHAR(30) NOT NULL
);









-- INSERTING INTO TABLES
INSERT INTO ADMINISTRATOR_TABLE_1 VALUES(1,'KODIDELA AJAY KUMAR REDDY','ajay0304');
INSERT INTO ADMINISTRATOR_TABLE_1 VALUES(2,'KODIDELA CHAITANYA KUMAR REDDY','chai0304');